title: cleo miao

description: cleo miao portfolio website
show_downloads: true
google_analytics:
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - yarn.lock
  - package.json
  - hot
  - LICENSE.txt

plugins:


permalink: /:title/
